UPLOADS_DIR = "uploads"

SUPPORTED_AUDIO_FILE_TYPES = [
    "3ga",
    "8svx",
    "aac",
    "ac3",
    "aif",
    "aiff",
    "alac",
    "amr",
    "ape",
    "au",
    "dss",
    "flac",
    "flv",
    "m4a",
    "m4b",
    "m4p",
    "m4r",
    "mp3",
    "mpga",
    "ogg",
    "oga",
    "mogg",
    "opus",
    "qcp",
    "tta",
    "voc",
    "wav",
    "wma",
    "wv",
]

SUPPORTED_VIDEO_FILE_TYPES = ["webm", "mts", "m2ts", "mov", "mp2", "mov", "mp4", "mxf"]

SUPPORTED_LANGUAGES = [
    {"name": "Global English", "code": "en"},
    {"name": "Australian English", "code": "en_au"},
    {"name": "British English", "code": "en_uk"},
    {"name": "US English", "code": "en_us"},
    {"name": "Spanish", "code": "es"},
    {"name": "French", "code": "fr"},
    {"name": "German", "code": "de"},
    {"name": "Italian", "code": "it"},
    {"name": "Portuguese", "code": "pt"},
    {"name": "Dutch", "code": "nl"},
    {"name": "Hindi", "code": "hi"},
    {"name": "Japanese", "code": "ja"},
    {"name": "Chinese", "code": "zh"},
    {"name": "Finnish", "code": "fi"},
    {"name": "Korean", "code": "ko"},
    {"name": "Polish", "code": "pl"},
    {"name": "Russian", "code": "ru"},
    {"name": "Turkish", "code": "tr"},
    {"name": "Ukrainian", "code": "uk"},
    {"name": "Vietnamese", "code": "vi"},
]

ENGLISH_STOPWORDS = [
    "i",
    "me",
    "my",
    "myself",
    "we",
    "our",
    "ours",
    "ourselves",
    "you",
    "your",
    "yours",
    "yourself",
    "yourselves",
    "he",
    "him",
    "his",
    "himself",
    "she",
    "her",
    "hers",
    "herself",
    "it",
    "its",
    "itself",
    "they",
    "them",
    "their",
    "theirs",
    "themselves",
    "what",
    "which",
    "who",
    "whom",
    "this",
    "that",
    "these",
    "those",
    "am",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "have",
    "has",
    "had",
    "having",
    "do",
    "does",
    "did",
    "doing",
    "a",
    "an",
    "the",
    "and",
    "but",
    "if",
    "or",
    "because",
    "as",
    "until",
    "while",
    "of",
    "at",
    "by",
    "for",
    "with",
    "about",
    "against",
    "between",
    "into",
    "through",
    "during",
    "before",
    "after",
    "above",
    "below",
    "to",
    "from",
    "up",
    "down",
    "in",
    "out",
    "on",
    "off",
    "over",
    "under",
    "again",
    "further",
    "then",
    "once",
    "here",
    "there",
    "when",
    "where",
    "why",
    "how",
    "all",
    "any",
    "both",
    "each",
    "few",
    "more",
    "most",
    "other",
    "some",
    "such",
    "no",
    "nor",
    "not",
    "only",
    "own",
    "same",
    "so",
    "than",
    "too",
    "very",
    "s",
    "t",
    "can",
    "will",
    "just",
    "don",
    "should",
    "now",
    "d",
    "ll",
    "m",
    "o",
    "re",
    "ve",
    "y",
]
